openapi: 3.0.0
info:
  title: Hello People
  description: people API
  version: v1
paths:
  /people/{id}:
    get:
      summary: Returns a single person
      parameters: 
        - name: id
          in: path
          description: ID of a person to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Person specified is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              examples:
                Tony:
                  value:
                    id: 1
                    name: Tony McGrady
                    birthDate: 1965-12-15
                    countryOfBirth: USA
                Julia:
                  value:
                    id: 2
                    name: Julia Smith
                    birthDate: 1987-04-23
                    countryOfBirth: USA
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a person from the list
      parameters:
        - name: id
          in: path
          description: ID of a person to delete
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '202':
          description: Person successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update an existing person
      parameters: 
        - name: id
          in: path
          description: ID of a person to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPerson'
            example:
              name: Chen Hui Zhen
              birthDate: 1977-07-07
              countryOfBirth: China
      responses:
        '202':
          description: Person successfully updated
    post:
      summary: Adds a new person to the list
      parameters: 
        - name: id
          in: path
          description: ID of a person to add
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPerson' 
      responses:
          '201':
            description: Person posted successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Person'
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
      
components:
  schemas:
    Person:
      allOf:
        - $ref: '#/components/schemas/NewPerson'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64
              example: 102
    NewPerson:
      required:
        - name
      properties:
        name:
          type: string
        birthDate:
          type: string
        countryOfBirth:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
            
          
                      
